arenaxr/arena-web-core

intro-dialog/intro_dialog.js
intro-dialog/style.css
mqtt-chat/main.js
mqtt-chat/mqtt-chat.js
mqtt-chat/style.css

Intro dialog and chat

---

face-tracking/script.js
icons/icons.js
jitsi-arena.js

fixed slot for screenshare, increase opacity for avatar video

---

icons/icons.js

Add newsettings event

---

events.js
mqtt.js

fix warp from onConnectionLost, corrected some error logging

---

build/arena-obj3d.json
build/index.html
build/main.js
build/persist-objects.js
mqtt-chat/mqtt-chat.js

Fix find user rotation
Better build defaults
Select all button

Small improvements to build and chat

---

mqtt-chat/mqtt-chat.js
mqtt-chat/style.css

Several fixes to chat.
Close #84 
Close #77

Chat fixes

---

mqtt-chat/mqtt-chat.js
mqtt-chat/style.css

Merging alerts and confirmation; Still working on landmarks.

Chat landmarks

---

build/arena-landmarks.json
build/arena-scene-options.json
build/main.js
build/persist-objects.js

Build landmarks

---

build/arena-scene-options.json
build/index.html
build/main.js
build/persist-objects.js

Several fixes/improvements to build.

Build improvements

---

build/arena-obj3d.json

Now supports: video-control, material, multisrc, light, animation, animation-mixer, sound, dynamic-body, impulse, collision-listener, goto-url

Added direct support for several a-frame components

---

jitsi-arena.js
mqtt.js

This does *not* gracefully handle a webcam being plugged in after the initial failure. 
There are still occasionally some oddities with async behavior if the webcam permission is left ignored for a while then denied.
Some of this may become moot when the startup flow UI is introduced

Handle no webcam or not-permitted webcam to Jitsi

---

build/index.html
header.html
network/index.html

Note: Uses unsupported Bootstrap 2.3.2 libs to avoid clashing with build page styling for now.

Add build, network page navbar draft

---

build/arena-scene-options.json
src/arena.js
src/event-emitter.js
src/message-actions/create-update.js
src/mqtt.js
src/utils.js

Start location

---

src/arena.js

Only enable vio after camera is added

---

src/arena.js
src/chat/index.js

Change topics to be within namespace

---

src/components/material-extras.js
src/message-actions/create-update.js

This sets renderOrder=0 and colorWrite=true in one shot:
{"material-extras":{"transparentOccluder": true}}
Can also be set individually:
{"material-extras":{"colorWrite": false}}
{"material-extras":{"renderOrder": 0}}
Close #224

Material extras occlusion

---

src/arena.js
src/ui/av-setup.js

Improvements to Setup AV popup onload

Setupav fix

---

build/schemas/image.json
build/schemas/threejs-scene.json
src/components/attribution.js
src/message-actions/create-update.js

Support dropbox cross origin src attributes

---

src/arena.js

This should fix the missing users from the chat list.

Fix saving namespace

---

src/arena.js

Apply start position rotation to look-controls component

---

package-lock.json
package.json
src/components/README.md
src/components/arena-camera.js
src/components/arena-user.js
src/components/arena-vive.js
src/components/armarker.js
src/components/attribution.js
src/components/click-listener.js
src/components/collision-listener.js
src/components/gesture-detector.js
src/components/goto-url.js
src/components/hide-in-ar-mode.js
src/components/impulse.js
src/components/index.js
src/components/load-scene.js
src/components/material-extras.js
src/components/network-latency.js
src/components/press-and-move.js
src/components/text-input.js
src/components/threejs-scene.js
src/components/ttl.js
src/components/video-control.js

Generate documentation for ARENA-specific components from jsdoc.

Component docs

---

build/main.js
package-lock.json
package.json
src/auth.js
src/chat/index.js
src/gltf-progress/index.js
src/icons/index.js

Went through the code and:
- When possible, replaced htmlElement.innerHTML for htmlElement.textContent (textContent should be XSS-safe)
- When needed, used 'he' (html entities library) to encode data: htmlElement.innerHTML = he.encode(theData)

Sanitize check

---

build/schemas/arena-program.json
src/arena.js
src/auth.js
src/icons/index.js
src/jitsi.js
src/ui/av-setup.js

Pass scene name and name space in separate variables

---

arts/index.html
arts/script.js
arts/style.css
header.html
navbar-auth-state.js

This should allow better debug of arts-started programs.

Arts UI update

---

src/aframe-mods/wasd-speed-controls.js
src/arena.js
src/chat/index.js
src/components/index.js
src/components/landmark.js
src/components/vendor/nav-system.js
src/icons/index.js
src/message-actions/create-update.js
src/mqtt.js

New Features:
Existing:
Cleanup:
Updates to other repos:
Resolves #138

Landmark refactor

---

src/chat/index.js

Display new message alert; Close #298

---

src/components/README.md
src/components/gesture-detector.js

Fixing link

---

src/message-actions/create-update.js

Remove unnecessary import

---

src/components/gltf-model-progress.js
src/components/gltf-progress-style.css

Gltf progress refactor

---

src/components/gltf-model-progress.js

Count failed towards percentage

---

arts/index.html
arts/script.js
arts/style.css
src/arena-console.js
src/arena.js
src/chat/index.js
src/index.js

Send console messages to pubsub. View them in /arts.

Pubsub logger

---

build/schemas/definitions-geometry.json
src/components/index.js
src/components/jitsi-video.js
src/event-emitter.js
src/jitsi.js
src/message-actions/client-event.js
src/message-actions/delete.js
src/message-actions/parser.js

Apply jitsi video stream to geometry

---

build/schemas/arena-scene-options.json
src/arena.js
src/components/material-extras.js
src/message-actions/create-update.js
src/utils.js

Small refactor of dropbox public share link support.

Dropbox url support

---

build/persist-objects.js
build/schemas/arena-scene-options.json
build/schemas/definitions-common.json
src/arena.js
src/chat/index.js
src/components/armarker.js
src/systems/armarker/apriltag-detector/apriltag.js
src/systems/armarker/armarker-reloc.js
src/systems/armarker/armarker.js
src/systems/armarker/camera-capture/ccarheadset.js
src/systems/armarker/camera-capture/ccwebarviewer.js
src/systems/armarker/camera-capture/ccwebxr.js
src/systems/armarker/worker-msgs.js
src/utils.js

1. Support the following ARMarker attributes
|                                  | Dynamic (dynamic=true)                                       | Static (dynamic=false)                                       |
| -------------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| **No Publish** (publish=false)   | **Use case: Objects moving with tag**                        | **Use case: Anchor scene in the real world**                 |
| **Publish** <br />(publish=true) | **Use case: External build script**<br />Not used for relocalization; Does not update scene object<br /> | **Use case: Experimental tag detection sharing**<br />Still used for relocalization<br /> |
2. Minor refactor and cleanup

Armarker attributes

---

src/arena-version.js
src/index.js

Add version message

---

network/index.html

fix: network graph (make graph.js a module)

---

src/components/index.js
src/components/thickline/index.js
src/components/thickline/lib/THREE.MeshLine.js

thickline is now part of our source (instead of an external dependency); fixed ShaderMaterial() instance creation problem; close #401

fix: add thickline to components; fix instantiation issue

---

src/components/README.md
src/components/arena-camera.js
src/components/arena-user.js

Add `videoCulling` on/off flag.

fix: Disable video culling by default

---

build/schemas/arena-scene-options.json
src/components/arena-camera.js
src/components/arena-user.js

Arena user refactor

---

CHANGELOG.md
build/schemas/arena-scene-options.json
src/components/README.md
src/components/arena-camera.js
src/ui/av-setup.js

Defined by  `"scene-options": { "sceneHeadModel": "/store/models/Head.gltf" }` for example.

feat(avatar): Added custom scene head model

---

arts/script.js
src/arena.js
src/runtime-mngr/index.js
src/runtime-mngr/mqtt-client.js

Module deletion and other minor fixes.

fix: Runtime manager module deletion

---

build/schemas/definitions-common.json
src/components/material-extras.js

278 material extras traverse

---

src/systems/armarker/armarker.js
src/systems/armarker/camera-capture/ccarheadset.js
src/systems/armarker/camera-capture/ccwebar.js

Mostly for HL2, various fixes to properly use GUM for marker relocalization CV pipeline

CC AR Headset fix

---

build/schemas/definitions-common.json
src/components/material-extras.js

apply render order to all objects
remove depthTest, needs testing

fix(material-extras): apply render order to all objects

---

build/schemas/arenaui-button-panel.json
build/schemas/arenaui-card.json
build/schemas/arenaui-prompt.json
src/components/ui/buttons.js
src/components/ui/card.js
src/components/ui/prompt.js
src/constants/ui.js

This is a bit darker than the figma appearance despite equal color codes, not sure why (doesn't appear to be effect of opacity values). Probably fine

UI dark mode

---

index.html
package-lock.json
package.json
src/systems/armarker/armarker.js
src/systems/core/mqtt.js
src/systems/core/workers/mqtt-worker.js
src/systems/webxr/debug-xr.js
src/systems/webxr/index.js
src/systems/webxr/mesh-dump.js
src/systems/webxr/webxr-env-publisher.js

Publishes detected meshes and planes to pubsub
Depends on arenaxr/arena-account#83 for permissions to new `realm/env` topic tree

Add env sensing 

---

src/systems/postprocessing/shaders/compositor-shader.js
src/systems/postprocessing/shaders/glsl/compositor/frag.glsl

Merged reproject movement function from Arena renderfusion playground. Added reprojectMovement flag into compositor-shader.js

Add translational time warping for renderfusion client

---

build/schemas/arena-schema-files.json
build/schemas/urdf-model.json
src/components/object/index.js
src/components/object/pcd-model.js
src/components/object/urdf-model.js
src/components/vendor/urdf-loader/README.md
src/components/vendor/urdf-loader/URDFClasses.d.ts
src/components/vendor/urdf-loader/URDFClasses.js
src/components/vendor/urdf-loader/URDFDragControls.js
src/components/vendor/urdf-loader/URDFLoader.d.ts
src/components/vendor/urdf-loader/URDFLoader.js
src/components/vendor/urdf-loader/three-example-loaders/ColladaLoader.js
src/components/vendor/urdf-loader/three-example-loaders/STLLoader.js
src/components/vendor/urdf-loader/three-example-loaders/TGALoader.js
src/components/vendor/urdf-loader/urdf-manipulator-element.js
src/components/vendor/urdf-loader/urdf-viewer-element.js

Add urdf-model component.
See example: https://arena-dev1.conix.io/npereira/urdf
close #632

URDF Loader

---

build/index.html
build/main.js
build/persist-objects.js

Basic program management. **Only stop scene instance programs**.

Program buttons

---

build/persist-objects.js

fix: make sure subscribe is only called after connect

---

build/schemas/definitions-common.json
index.html
src/components/object/text-input.js
src/style/arena.css
src/systems/webxr/webxr-device-manager.js
src/systems/webxr/webxr-viewer.js

Where previously this worked for just desktop, now handles webxr viewer on ios as well as chrome touch.
Currently does not handle immersive HMD session such as on quest

Improve text input during immersive xr session
